 # NumPy
## Introducción a NumPy

NumPy es una biblioteca fundamental para la computación científica en Python. Ofrece un objeto de arreglo multidimensional, diversos objetos derivados (como matrices y matrices enmascaradas), y una variedad de rutinas para operaciones rápidas en arreglos, incluyendo matemáticas, lógica, manipulación de formas, clasificación, selección, I/O, transformadas de Fourier, álgebra lineal, operaciones estadísticas, simulación aleatoria, y mucho más.


Creación y Manipulación de Arrays
NumPy permite crear arrays desde listas o tuplas en Python. Los arrays pueden ser de cualquier dimensión, y la biblioteca facilita operaciones matemáticas complejas en estos.


 ### Crear un Array Bidimensional


In [1]:

import numpy as np

# Crear un array 2D con números del 1 al 9
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Técnicas de Slicing y Acceso a Elementos
NumPy ofrece formas avanzadas de acceder a partes de arrays, conocidas como slicing, que permiten seleccionar rangos de datos.

## Acceder a Elementos
Extrae la segunda fila del array creado anteriormente.
Selecciona el elemento en la segunda columna y tercera fila.


In [2]:
import numpy as np

# Crear un array 2D con números del 1 al 9
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extraer la segunda fila del array
segunda_fila = array_2d[1, :]

# Seleccionar el elemento en la segunda columna y tercera fila
elemento_seleccionado = array_2d[2, 1]


# Diferencias entre Copia y Vista de Arrays
Es crucial entender la diferencia entre una copia de un array y una vista. Una copia es un nuevo array, mientras que una vista es solo una manera de ver los datos del array original.

Ejercicio: Copia vs. Vista
Crea una copia del array original y modifica un elemento. Verifica si el array original cambia.
Realiza una vista del mismo array y modifica un elemento. Observa si esto afecta al array original.

In [3]:
import numpy as np

# Crear un array 2D con números del 1 al 9 para el ejemplo
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Crear una copia del array original
array_copia = array_2d.copy()

# Modificar un elemento en la copia
array_copia[0, 0] = 100

# Crear una vista del array original
array_vista = array_2d.view()

# Modificar un elemento en la vista
array_vista[0, 1] = 200

# Mostrar el array original después de modificar la copia
print("Array original después de modificar la copia:")
print(array_2d)

# Mostrar el array original después de modificar la vista
print("\nArray original después de modificar la vista:")
print(array_2d)


Array original después de modificar la copia:
[[  1 200   3]
 [  4   5   6]
 [  7   8   9]]

Array original después de modificar la vista:
[[  1 200   3]
 [  4   5   6]
 [  7   8   9]]


# Métodos de Unión y Búsqueda en Arrays

NumPy ofrece métodos para combinar arrays y buscar elementos dentro de estos.



Ejercicio: Unir Arrays
Utiliza np.concatenate para unir dos arrays.
Busca elementos mayores a 5 en el array resultante.

In [4]:
import numpy as np

# Crear dos arrays para unir
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Unir los dos arrays
array_unido = np.concatenate((array1, array2))

# Buscar elementos mayores a 5 en el array resultante
elementos_mayores_a_5 = array_unido[array_unido > 5]


In [5]:
print(array_unido)
print(elementos_mayores_a_5)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10]


# Ordenamiento de Arrays
El ordenamiento es otra operación fundamental en NumPy, permitiendo ordenar los elementos dentro de un array.

Ejercicio: Ordenar un Array
Crea un array con números aleatorios y ordena sus elementos.

In [6]:
import numpy as np

# Crear un array con números aleatorios
array_aleatorio = np.random.randint(1, 100, size=10)  # Array de 10 elementos entre 1 y 99

# Ordenar los elementos del array
array_ordenado = np.sort(array_aleatorio)


In [7]:
print (array_aleatorio)
print (array_ordenado )

[ 2 31 37 53 90 29  9 33 49 68]
[ 2  9 29 31 33 37 49 53 68 90]


# Ejercicios Prácticos


Crea un array 3D y accede a un subconjunto específico de este.
Realiza operaciones matemáticas básicas (suma, resta, multiplicación) entre arrays.
Investiga y aplica funciones estadísticas básicas en un array (media, mediana, desviación estándar).

In [8]:
import numpy as np

# Crear un array 3D
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Acceder a un subconjunto específico
subconjunto = array_3d[0, 1, :]

# Suma, resta, multiplicación
suma = array_3d[0] + array_3d[1]
resta = array_3d[1] - array_3d[0]
multiplicacion = array_3d[0] * array_3d[1]

# Funciones estadísticas
media = np.mean(array_3d)
mediana = np.median(array_3d)
desviacion_estandar = np.std(array_3d)


In [9]:
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
print(subconjunto)

[4 5 6]


In [11]:
print(suma)
print(resta)
print(multiplicacion)

[[ 8 10 12]
 [14 16 18]]
[[6 6 6]
 [6 6 6]]
[[ 7 16 27]
 [40 55 72]]


In [ ]:
print(media)
print(mediana)
print(